compiler = gcc
name = syncrohyzationServer
name2 = clientX
executable = syncrohyzationServer
executable2 = clientX

$(name): $(name).c
	$(compiler) -o $(executable) $(name).c -lm
	$(compiler) -o $(executable2) $(name2).c

